-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, S.CATEGORY, S.TOTAL_SALES
FROM AUTHOR A
INNER JOIN (SELECT B.AUTHOR_ID, B.BOOK_ID, B.CATEGORY, SUM(B.PRICE * S.SALES) TOTAL_SALES
            FROM BOOK_SALES S
            INNER JOIN BOOK B
            ON B.BOOK_ID = S.BOOK_ID
            WHERE SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
            GROUP BY CATEGORY, AUTHOR_ID) S
ON A.AUTHOR_ID = S.AUTHOR_ID
ORDER BY A.AUTHOR_ID ASC, S.CATEGORY DESC;