-- 코드를 입력하세요

-- 완료된 중고 거래의 총 금액이 70만 원 이상인 사람을 조회

-- 완료된 중고 거래 조회

SELECT USER_INFO.USER_ID, USER_INFO.NICKNAME, ARTICLE.TOTAL_SALES
FROM USED_GOODS_USER USER_INFO
INNER JOIN (SELECT WRITER_ID, SUM(PRICE) TOTAL_SALES
            FROM USED_GOODS_BOARD
            WHERE STATUS = 'DONE'
            GROUP BY WRITER_ID
              HAVING SUM(PRICE) >= 700000) ARTICLE
        ON ARTICLE.WRITER_ID = USER_INFO.USER_ID
ORDER BY ARTICLE.TOTAL_SALES ASC;