
SELECT B.CATEGORY, SUM(S.SALES) TOTAL_SALES
FROM (
    -- 도서 카테고리 조회
    SELECT B.CATEGORY
    FROM BOOK B
    GROUP BY B.CATEGORY) B
    INNER JOIN (
        -- 2022년 1월의 책별 도서 판매량 조회
        SELECT B.CATEGORY, SALES
        FROM BOOK B
            INNER JOIN BOOK_SALES BS
            ON B.BOOK_ID = BS.BOOK_ID
                AND YEAR(BS.SALES_DATE) = '2022'
                AND MONTH(BS.SALES_DATE) = '01') S
    ON B.CATEGORY = S.CATEGORY
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;